# encoding: UTF-8
require_relative './users'
require_relative './cars'
require_relative './colors'
require_relative './courses'
require_relative './fuels'
require_relative './offers'
require_relative './query'
require_relative './location'
require_relative './rides'
